/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9c7ea83f8a10cecdc1ad461ad729a29f)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ROOM: DurableObjectNamespace<import("./src/index").Room>;
	MATCH_ROOM: DurableObjectNamespace<import("./src/index").MatchRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Room" | "MatchRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
