/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: db12eac219933ad0afd90af09a232de4)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ROOM: DurableObjectNamespace<import("./src/index").Room>;
	MATCH_ROOM: DurableObjectNamespace<import("./src/index").MatchRoom>;
	LOBBY: DurableObjectNamespace<import("./src/index").Lobby>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Room" | "MatchRoom" | "Lobby";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
