/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1c1cb8cebe711fcd41ba1e7fa769c5e6)
interface __BaseEnv_Env {
	AUTH_DB: D1Database;
	ASSETS: Fetcher;
	ROOM: DurableObjectNamespace<import("./src/index").Room>;
	MATCH_ROOM: DurableObjectNamespace<import("./src/index").MatchRoom>;
	LOBBY: DurableObjectNamespace<import("./src/index").Lobby>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Room" | "MatchRoom" | "Lobby";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
